adam_epsilon: 1.0e-08
cache_dir: ''
config_name: ''
data_dir: train_test_data/
do_predict: true
do_train: true
eval_batch_size: 4
fp16: false
fp16_opt_level: O1
gradient_accumulation_steps: 1
learning_rate: 0.001
max_grad_norm: 1.0
max_source_length: 1024
max_target_length: 56
model_name_or_path: facebook/bart-large-cnn
n_gpu: 8
n_tpu_cores: 0
num_train_epochs: 200
output_dir: /home/zhanj289/side_projects/cord_19_sum/summarization/bart/bart_utest_output
seed: 42
tokenizer_name: ''
train_batch_size: 4
warmup_steps: 0
weight_decay: 0.0
